# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  coveralls: coveralls/coveralls@1.0.6

executors:
  c-build-env:
    docker:
      - image: ubuntu:20.04

jobs:
  coverage:
    executor: c-build-env
    steps:
      - run: DEBIAN_FRONTEND=noninteractive apt update
      - run: DEBIAN_FRONTEND=noninteractive apt install -y build-essential liblua5.3-dev lua5.3 git cmake valgrind lcov npm texlive-latex-base texlive-latex-recommended texlive-latex-extra graphviz gcovr
      - run: rm -rf luacpp
      - checkout
      - run: pwd && ls -ltr
      - run: mkdir build
      - run: cd build && cmake -DCMAKE_BUILD_TYPE=Coverage ../Source && make -j4
      - run: cd build && make coverage-cli
      - run: cd build && make coverage-lcov
      - coveralls/upload:
         verbose: true
         path_to_lcov: build/coverage.info

  memory:
    executor: c-build-env
    steps:
      - run: DEBIAN_FRONTEND=noninteractive apt update
      - run: DEBIAN_FRONTEND=noninteractive apt install -y build-essential liblua5.3-dev lua5.3 git cmake valgrind lcov npm texlive-latex-base texlive-latex-recommended texlive-latex-extra graphviz gcovr
      - run: rm -rf luacpp
      - checkout
      - run: pwd && ls -ltr
      - run: mkdir debug
      - run: cd debug && cmake -DCMAKE_BUILD_TYPE=Debug ../Source && make -j4
      - run: cd debug && make test_memory
      
workflows:
  # Name the workflow "welcome"
  build:
    # Run the welcome/run job in its own container
    jobs:
      - coverage
      - memory
